import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Dropdown from "../components/Dropdown/Dropdown";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>React UI Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>React UI Test</h1>
        <a
          href="https://github.com/jonatasoc/react-ui-test"
          className={styles.linkText}
        >
          See code on Github{" "}
        </a>

        <Dropdown />
      </main>

      <footer className={styles.footer}>
        <span>Made by</span>
        <a
          href="https://github.com/jonatasoc"
          style={{
            display: "flex",
            alignItems: "center",
          }}
        >
          <Image
            src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
            width={30}
            height={30}
            alt="github icon"
          />
          @jonataoc
        </a>
      </footer>
    </div>
  );
};

export default Home;
